version: "3"
services:
  app:
    build: php
    volumes:
      - ./app:/var/www

  nginx:
    image: nginx:1.17-alpine
    depends_on:
      - app
    ports:
      - 3000:8000
    volumes:
      - ./app:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx

  db:
    image: mysql:5.7.22
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    env_file: .env
    ports:
      - "3307:3306"
